# Generated by Django 6.0.1 on 2026-02-03 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('os_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='mdm.fleet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fleet',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_fleet_name_per_owner'),
        ),
    ]
